/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2019-09-03 12:49:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hcl.employee.EmployeeDetails;
import com.hcl.employee.EMSBal;
import com.hcl.employee.LeaveHistory;
import java.util.List;
import org.apache.jasper.tagplugins.jstl.core.ForEach;

public final class ApproveDeny_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.hcl.employee.EMSBal");
    _jspx_imports_classes.add("org.apache.jasper.tagplugins.jstl.core.ForEach");
    _jspx_imports_classes.add("com.hcl.employee.EmployeeDetails");
    _jspx_imports_classes.add("com.hcl.employee.LeaveHistory");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

int leaveid = Integer.parseInt(request.getParameter("applystatus"));
LeaveHistory lh = EMSBal.approveDenyBal(leaveid);
EmployeeDetails e = EMSBal.searchBal(lh.getEmpId());

      out.write("\r\n");
      out.write("\t<center>\r\n");
      out.write("     <table border=\"1\">\r\n");
      out.write("     <tr>\r\n");
      out.write("        <th>Employee Id</th>\r\n");
      out.write("        <td ><input type=\"text\" name=\"empId\" value=\"");
      out.print(lh.getEmpId());
      out.write("\" readonly=\"readonly\"/></td>\r\n");
      out.write("        <th>Start Date</th>\r\n");
      out.write("        <td ><input type=\"text\" name=\"sd\" value=\"");
      out.print(lh.getSd());
      out.write("\" readonly=\"readonly\"/></td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("        <th>Employee Name</th>\r\n");
      out.write("        <td ><input type=\"text\" name=\"name\" value=\"");
      out.print(e.getEmpName());
      out.write("\" readonly=\"readonly\"/></td>\r\n");
      out.write("        <th>End Date</th>\r\n");
      out.write("        <td ><input type=\"text\" name=\"ed\" value=\"");
      out.print(lh.getEd());
      out.write("\" readonly=\"readonly\"/></td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("        <th>Leave Balance</th>\r\n");
      out.write("        <td ><input type=\"text\" name=\"empLeaveBal\" value=\"");
      out.print(e.getEmpLeaveBal());
      out.write("\" readonly=\"readonly\"/></td>\r\n");
      out.write("        <th>Number Of Days</th>\r\n");
      out.write("        <td ><input type=\"text\" name=\"noofDays\" value=\"");
      out.print(lh.getNoofDays());
      out.write("\" readonly=\"readonly\"/></td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("          <th>Leave Type</th>\r\n");
      out.write("          <td><input type=\"text\" name=\"leaveType\" value=\"");
      out.print(lh.getLeaveType());
      out.write("\" readonly=\"readonly\"/></td>\r\n");
      out.write("          <center><td rowspan=\"3\"><input type = \"submit\" value = \"Approve\" /></td></center>\r\n");
      out.write("          <td rowspan=\"3\"><input type = \"submit\" value = \"Deny\" /></td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("          <th>Reason</th>\r\n");
      out.write("          <td ><input type=\"text\" name=\"reason\" value=\"");
      out.print(lh.getReason());
      out.write("\" readonly=\"readonly\"/></td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("         <th>Comments</th>\r\n");
      out.write("         <td ><input type=\"text\" name=\"mgrComments\" /></td>\r\n");
      out.write("     </table>\r\n");
      out.write("     </center>\r\n");
      out.write("\t \r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
